- name: Build firmware
      run: |
        cp build.config padavan-ng/trunk/.config
        pushd padavan-ng/trunk
        # Полная очистка исходников от "мусора" предыдущих сборок
        make mrproper
        # Принудительная очистка BusyBox
        make -C user/busybox clean || true
        # Восстановление конфига после mrproper
        cp ../../build.config .config
        # Сборка с детальным логом для отладки
        make V=s
        ./build_firmware.sh
        popd
